[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# TODO: UPDATE WITH FINAL HARDWARE DESIGN
runner = "probe-rs run --chip STM32L476VG"

[build]
# TODO: MAKE SURE THIS IS CORRECT WITH FINAL BOARD DESIGN
# For Cortex-M4 processors
target = "thumbv7em-none-eabi"

[alias]
rr = "run --release"
br = "build --release"

epsr = "run --release -p eps"
epsb = "build --release -p eps"

libtest = "test -p shared -Zbuild-std --target aarch64-apple-darwin"
