name: Format

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@nightly
      with:
        components: rustfmt
    - name: Run cargo fmt
      run: cargo fmt
    # Commit changes
    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
          commit_message: format