name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@nightly
      with:
        targets: aarch64-apple-darwin, thumbv7em-none-eabi
        components: rust-src
    - name: Build
      run: cargo build --release --target thumbv7em-none-eabi
    - name: Run tests
      run: cargo test -Zbuild-std --target x86_64-unknown-linux-gnu
