name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install nightly rust
      run: rustup toolchain install nightly
    - name: Make nightly default
      run: rustup default nightly
    - name: Install build target
      run: rustup target add thumbv7em-none-eabi
    - name: Print installed toolchains
      run: rustup show
    - name: Build
      run: cargo build --release --target thumbv7em-none-eabi
    - name: Install test target
      run: rustup target add aarch64-apple-darwin
    - name: Add rust src
      run: rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu
    - name: Run tests
      run: cargo test -Zbuild-std --target x86_64-unknown-linux-gnu
