name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install nightly rust
      run: rustup update nightly
    - name: Install build target
      run: rustup target add thumbv7em-none-eabi
    - name: Build
      run: cargo +nightly build --release
    - name: Install test target
      run: rustup target add aarch64-apple-darwin
    - name: Run tests
      run: cargo test -Zbuild-std --target aarch64-apple-darwin
